.nh
.TH "CERT" "1" "Nov 2025" "github.com/kisom/cert" ""

.SH NAME
cert - A certificate swiss‑army knife


.SH SYNOPSIS
\fBcert [flags]\fP


.SH DESCRIPTION
cert is a small command‑line tool for inspecting and working with X.509/TLS
certificates and connections. It consolidates several utilities from kisom/goutils
into a single binary using the Cobra CLI framework. Use --help on any subcommand
to see details and examples.

.PP
A note on targets: most commands accept a list of targets, which can be either
remote hosts or local files. cert will first check whether the target is a file
on disk; if it is not, it will attempt to treat the target as a remote host.
Valid formats for remote hosts are:
.IP \(bu 2
host:port
\[la]defaulting to port 443\[ra]
.IP \(bu 2
https URLs, including host:port
.IP \(bu 2
tls://host[:port]

.PP
Generally, the tools will not proceed past the handshake state when connecting to
a remote host.


.SH OPTIONS
\fB--ca\fP=""
	CA certificate bundle file

.PP
\fB--config\fP=""
	config file (default is $HOME/.config/goutils/cert.yaml)

.PP
\fB--debug\fP[=false]
	enable debug mode

.PP
\fB-d\fP, \fB--display-mode\fP="lower"
	hex display mode for SKI

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for cert

.PP
\fB-i\fP, \fB--intermediates-file\fP=""
	intermediate certificate bundle

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	enable quiet mode

.PP
\fB-k\fP, \fB--skip-verify\fP[=false]
	skip certificate verification

.PP
\fB--strict-tls\fP[=false]
	use strict TLS settings

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBcert-bundler(1)\fP, \fBcert-ca-signed(1)\fP, \fBcert-completion(1)\fP, \fBcert-csrpub(1)\fP, \fBcert-doc(1)\fP, \fBcert-docgen(1)\fP, \fBcert-dump(1)\fP, \fBcert-expiry(1)\fP, \fBcert-filetype(1)\fP, \fBcert-gencsr(1)\fP, \fBcert-genkey(1)\fP, \fBcert-matchkey(1)\fP, \fBcert-pem(1)\fP, \fBcert-selfsign(1)\fP, \fBcert-serial(1)\fP, \fBcert-signcsr(1)\fP, \fBcert-ski(1)\fP, \fBcert-stealchain(1)\fP, \fBcert-tlsinfo(1)\fP, \fBcert-verify(1)\fP, \fBcert-version(1)\fP


.SH HISTORY
21-Nov-2025 Auto generated by spf13/cobra
